version: '2'
services:
  app:
    container_name: app
    build: .
    command: npm run docker-test
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-1
    image: mongo
    ports:
      - "27017:27017"